# Site settings
title: Hi, I'm Pankaj.
description: Pankaj Chouhan's professional portfolio site
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Pankaj Chouhan
user_title: Dr.
user_job_title: DS/ML Aficionado. Python/SQL Coder.
email: pankajchouhan93552 [at] gmail.com
twitter_username: pkjchauhan9355
github_username:  pc-fsu

exclude: ['package.json', 'src' , 'node_modules']
